name: 'Welcome New Contributors'

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greet the contributor'
        uses: garg3133/welcome-new-contributors@a38583ed8282e23d63d7bf919ca2d9fb95300ca6  # v1.2 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            Hey @contributor_name! Thanks for opening your first issue. We appreciate your contribution and welcome you to our community! 
            We are glad to have you here and to have your input on Daily Selfie. 
          pr-message: >
            Hi @contributor_name! Welcome to our community and thank you for opening your first Pull Request. 
            Someone will review it soon. Thank you for committing to making Daily Selfie better.
          bot_token: ${{ secrets.BOT_ACCESS_TOKEN }}
          is-oauth-token: true
          issue-message-for-bot: 'Hello there, thanks for opening your first issue. We welcome you to the community!'
          pr-message-for-bot: 'Hello there, thanks for opening your first Pull Request. One of the maintainers will review it soon.'
